services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge

volumes:
  postgres:
